config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'

  devise_for :users, controllers: { confirmations: 'users/confirmations',
                                    omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  resources :chats
  resources :common_chat_messages, only: [:create]
  get 'freekassa/new' => 'freekassa#new', as: :freekassa_new
  post 'freekassa/create' => 'freekassa#create', as: :freekassa_create
  get 'freekassa/confirm/:id' => 'freekassa#confirm', as: :freekassa_confirm
  post 'freekassa/result' => 'freekassa#result', as: :freekassa_result
  get 'freekassa/fail' => 'freekassa#fail', as: :freekassa_fail
  get 'freekassa/index' => 'freekassa#index', as: :freekassa_index

  resources :messages
  resources :chat_rooms
  get 'prepend_personal_message' => 'chat_rooms#prepend_personal_message', as: :prepend_personal_message
  ActiveAdmin.routes(self)
  resources :devnews, :homepages, :profiles, :avatars, :improves, :orders, :getmoneys, :getbalances, :feedbacks, :payeers

  #scope ":locale", locale: /en|ru/ do
    post 'buyall/:id' => 'improves#buyall', as: 'buyall'

    put 'buyallproviant/:id' => 'profiles#buyallproviant', as: 'buyallproviant'

    post 'buynumb/:id' => 'profiles#buynumb', as: 'buynumb'
    post 'imroveses/:id' => 'improves#imroveses', as: 'imroveses'


    put 'buyaerodrome/:id' => 'improves#buyaerodrome', as: 'buyaerodrome'
    put 'buyradist/:id' => 'improves#buyradist', as: 'buyradist'
    put 'getbonus/:id' => 'profiles#getbonus', as: 'getbonus'

    get 'service' => 'homepages#service', as: 'service'
    get 'contact' => 'homepages#contact', as: 'contact'
    get 'faq' => 'profiles#faq', as: 'faq'


    get 'mobline' => 'profiles#mobline', as: 'mobline'
    get 'partner' => 'profiles#partner', as: 'partner'

    root 'homepages#index'
  #end

    match '/success' => 'orders#success', via: :get
    match '/fail' => 'orders#fail', via: :get
    match 'payeer/success' => 'payeers#success', via: :get
    match 'payeer/fail' => 'payeers#fail', via: :get

  get '*path', to: redirect("/#{I18n.default_locale}")

  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
  has_many :unread_messages, dependent: :destroy
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.user = current_user
    respond_to do |format|
      if @message.save
        user = @message.chat_room.users.where.not(id: current_user.id).first
        unread = @message.unread_messages.build
        unread.user_id = user.id
        unread.save
        ActionCable.server.broadcast "chat_room_#{@message.chat_room_id}", {
            message: MessagesController.render(
                partial: 'messages/message',
                locals: { message: @message }
            ).squish
        }

        @message.chat_room.users.each do |user|
          ActionCable.server.broadcast "personal_messages_#{user.id}",
                                       { message_id: @message.id }
        end
        
        format.js
        format.html { redirect_to :back, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body, :chat_room_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(message) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :chat_room_id %>
    <%= f.text_field :chat_room_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="single_dialog">
  <div class="dialog_ico">

    <% ava = message.user.avatars.last %>
    <% if ava.nil? %>
        <%= image_tag('img.jpg', width: 60) %>
    <% else %>
        <img src="<%= image_path ava.image.url(:thumb) %>" width="60" alt="Profile Image">
    <% end %>

    <span class="name_dialog"><%= message.user.name %></span> в
    <span class="last_message"><%= message.created_at.strftime('%d/%m/%Y %H:%M') %></span>
    написал:
  </div>
  <div class="single_dialog_info">
    <p class="last_message"><strong>
      <%= message.body %>
    </strong></p>

  </div>
</div>
<hr>

app/views/messages/_message_notify.html.erb
<li>
  <a>
    <p>
      <% ava = message.user.avatars.last %>
      <% if ava.nil? %>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" width="40" /></span>
      <% else %>
        <span class="image">
          <img src="<%= image_path ava.image.url(:thumb) %>" width="40" alt="Profile Image">
        </span>
      <% end %>


      <span>

      <span><%= message.user.name %></span> <br>
      <span class="time"><%= message.created_at.strftime('%d/%m/%Y %H:%M') %> </span>
    </span>
    </p>

    <span class="message">
      <%= message.body %>
    </span>
  </a>
</li>

app/views/messages/create.js.erb
$("#message_body").val("");

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Chat room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.body %></td>
        <td><%= message.chat_room %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>Chat room:</strong>
  <%= @message.chat_room %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>