config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'

  devise_for :users, controllers: { confirmations: 'users/confirmations',
                                    omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  resources :chats
  resources :common_chat_messages, only: [:create]
  get 'freekassa/new' => 'freekassa#new', as: :freekassa_new
  post 'freekassa/create' => 'freekassa#create', as: :freekassa_create
  get 'freekassa/confirm/:id' => 'freekassa#confirm', as: :freekassa_confirm
  post 'freekassa/result' => 'freekassa#result', as: :freekassa_result
  get 'freekassa/fail' => 'freekassa#fail', as: :freekassa_fail
  get 'freekassa/index' => 'freekassa#index', as: :freekassa_index

  resources :messages
  resources :chat_rooms
  get 'prepend_personal_message' => 'chat_rooms#prepend_personal_message', as: :prepend_personal_message
  ActiveAdmin.routes(self)
  resources :devnews, :homepages, :profiles, :avatars, :improves, :orders, :getmoneys, :getbalances, :feedbacks, :payeers

  #scope ":locale", locale: /en|ru/ do
    post 'buyall/:id' => 'improves#buyall', as: 'buyall'

    put 'buyallproviant/:id' => 'profiles#buyallproviant', as: 'buyallproviant'

    post 'buynumb/:id' => 'profiles#buynumb', as: 'buynumb'
    post 'imroveses/:id' => 'improves#imroveses', as: 'imroveses'


    put 'buyaerodrome/:id' => 'improves#buyaerodrome', as: 'buyaerodrome'
    put 'buyradist/:id' => 'improves#buyradist', as: 'buyradist'
    put 'getbonus/:id' => 'profiles#getbonus', as: 'getbonus'

    get 'service' => 'homepages#service', as: 'service'
    get 'contact' => 'homepages#contact', as: 'contact'
    get 'faq' => 'profiles#faq', as: 'faq'


    get 'mobline' => 'profiles#mobline', as: 'mobline'
    get 'partner' => 'profiles#partner', as: 'partner'

    root 'homepages#index'
  #end

    match '/success' => 'orders#success', via: :get
    match '/fail' => 'orders#fail', via: :get
    match 'payeer/success' => 'payeers#success', via: :get
    match 'payeer/fail' => 'payeers#fail', via: :get

  get '*path', to: redirect("/#{I18n.default_locale}")

  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")
  
end

app/controllers/freekassa_controller.rb
class FreekassaController < ApplicationController
  protect_from_forgery except: [:result]
  before_action :authenticate_user!, except: [:result]

  def index
  end

  def new
    @order = Payeer.new
  end

  def create
    @order = current_user.payeers.create(order_params)
    if @order.save

      redirect_to freekassa_confirm_path(@order)
    else
      redirect_to root_path
    end
  end

  def confirm
    @order = Payeer.find(params[:id])
    redirect_to root_path unless @order.user == current_user # && !@order.finished?
    @merchant_id = '50878'
    @secret_word = '4arp3nje'
    @order_id = @order.id.to_s
    @order_amount = @order.total.to_s
    @sign = Digest::MD5.hexdigest(@merchant_id + ':' + @order_amount + ':' + @secret_word + ':' + @order_id)
  end

  def result
    @merchant_id = '50878'
    @secret_word2 = '9155h78l'
    @params = request.params
    @amount = params['AMOUNT']
    @order_id = params['MERCHANT_ORDER_ID'].to_i
    @sign = params['SIGN']
    @order = Payeer.find(@order_id)
    @sample_sign = Digest::MD5.hexdigest("#{@merchant_id}:#{@order.total}:#{@secret_word2}:#{@order.id}")
    ref_balance = Transfer.find_by_user_id(@order.user.id)
    if @sign == @sample_sign
      if ref_balance.nil?
        transfer = Transfer.new
        transfer.user_id = params['us_user_uid'].to_i
        transfer.bank_id = Bank.last.id
        transfer.summa = @order.total
        transfer.save
      else
        ref_balance.summa += @order.total
        ref_balance.save
      end
      render :json => '{response: "YES"}'
    else
      redirect_to freekassa_fail_path
    end
  end

  def fail
  end

  private

  def order_params
    params.require(:payeer).permit(:total)
  end
end

app/helpers/freekassa_helper.rb
module FreekassaHelper
end

app/views/freekassa/confirm.html.erb
<h2>Плательщик: <%= @order.user.name %></h2>
<h2>Сумма: <%= @order.total %></h2>
<form method='get' action='http://www.free-kassa.ru/merchant/cash.php'>
  <input type='hidden' name='m' value='<%= @merchant_id %>'>
  <input type='hidden' name='oa' value='<%= @order_amount.to_s %>'>
  <input type='hidden' name='o' value='<%= @order_id %>'>
  <input type='hidden' name='s' value='<%= @sign %>'>
  <input type='hidden' name='us_user_uid' value='<%= current_user.id %>'>
  <input type='submit' name='pay' value='Продолжить платеж' class="btn btn-info">
</form>

app/views/freekassa/fail.html.erb
Ошибка при проведении платежа
<%= link_to 'На главную', root_path %>

app/views/freekassa/index.html.erb
<h2>Платежь проведен</h2>
<%= link_to 'Через несколько минут проверьте свой баланс', profiles_path %>

app/views/freekassa/new.html.erb
<center>
  <%= form_for :payeer, url: freekassa_create_path, method: :post do |f| %>

      <div class="register_form">
        <h1 class="register_form_title">Пополнение через free-kassa.ru</h1>

        <div class="register_form_field">
          <label for="password">Сумма</label>
          <%= f.number_field :total %>
        </div>
        <div class="register_form_submit">
          <input type="submit" value="Оплатить">
        </div>
  <% end %>
</center>