config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'

  devise_for :users, controllers: { confirmations: 'users/confirmations',
                                    omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  resources :chats
  resources :common_chat_messages, only: [:create]
  get 'freekassa/new' => 'freekassa#new', as: :freekassa_new
  post 'freekassa/create' => 'freekassa#create', as: :freekassa_create
  get 'freekassa/confirm/:id' => 'freekassa#confirm', as: :freekassa_confirm
  post 'freekassa/result' => 'freekassa#result', as: :freekassa_result
  get 'freekassa/fail' => 'freekassa#fail', as: :freekassa_fail
  get 'freekassa/index' => 'freekassa#index', as: :freekassa_index

  resources :messages
  resources :chat_rooms
  get 'prepend_personal_message' => 'chat_rooms#prepend_personal_message', as: :prepend_personal_message
  ActiveAdmin.routes(self)
  resources :devnews, :homepages, :profiles, :avatars, :improves, :orders, :getmoneys, :getbalances, :feedbacks, :payeers

  #scope ":locale", locale: /en|ru/ do
    post 'buyall/:id' => 'improves#buyall', as: 'buyall'

    put 'buyallproviant/:id' => 'profiles#buyallproviant', as: 'buyallproviant'

    post 'buynumb/:id' => 'profiles#buynumb', as: 'buynumb'
    post 'imroveses/:id' => 'improves#imroveses', as: 'imroveses'


    put 'buyaerodrome/:id' => 'improves#buyaerodrome', as: 'buyaerodrome'
    put 'buyradist/:id' => 'improves#buyradist', as: 'buyradist'
    put 'getbonus/:id' => 'profiles#getbonus', as: 'getbonus'

    get 'service' => 'homepages#service', as: 'service'
    get 'contact' => 'homepages#contact', as: 'contact'
    get 'faq' => 'profiles#faq', as: 'faq'


    get 'mobline' => 'profiles#mobline', as: 'mobline'
    get 'partner' => 'profiles#partner', as: 'partner'

    root 'homepages#index'
  #end

    match '/success' => 'orders#success', via: :get
    match '/fail' => 'orders#fail', via: :get
    match 'payeer/success' => 'payeers#success', via: :get
    match 'payeer/fail' => 'payeers#fail', via: :get

  get '*path', to: redirect("/#{I18n.default_locale}")

  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")
  
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  belongs_to :user

   has_attached_file :image,
                    styles: { medium: '100x100>', thumb: '200x200>'},
                    default_url: '/images/:style/missing.png'
   validates_attachment_content_type :image, 
                    content_type: ['image/jpeg', 'image/gif', 'image/png']

end

app/models/bank.rb
class Bank < ApplicationRecord
 has_many :transfers
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
	has_many :messages, dependent: :destroy
	has_many :subscriptions, dependent: :destroy
	has_many :users, through: :subscriptions

end

app/models/devnew.rb
class Devnew < ApplicationRecord
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/models/getbalance.rb
class Getbalance < ApplicationRecord
end

app/models/getmoney.rb
class Getmoney < ApplicationRecord
  belongs_to :user
end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
  has_many :unread_messages, dependent: :destroy
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
	def is_ik_payment_valid?(ik_cur, ik_am)
	 ( self.currency == ik_cur and self.total == ik_am )
	end
  	belongs_to :user
end

app/models/payeer.rb
class Payeer < ApplicationRecord
  belongs_to :user
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/systemfinance.rb
class Systemfinance < ApplicationRecord
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user
  belongs_to :bank
end

app/models/user.rb
class User < ApplicationRecord
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
    omniauth_providers: [:facebook, :twitter, :vkontakte]

  validates :name, presence: true, length: {maximum: 50}
  # validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  after_create :send_admin_mail

  # онлайн пользователи - User.online.count
  scope :online, lambda{ where("last_seen >= ?", 10.minutes.ago) }

  # def online?
  #   $redis_onlines.exists( self.id )
  # end

  def send_admin_mail

    self.send_confirmation_instructions
  end
  # after_create :send_admin_mail  

  # def send_admin_mail    
  #   Devise::Mailer.send_new_user_message(self).deliver  
  # end

  # def self.find_for_vkontakte_oauth(access_token)
  #   if user = User.where(:url => access_token.info.urls.Vkontakte).first
  #     user
  #   else 
  #     User.create!(:provider => access_token.provider, :url => access_token.info.urls.Vkontakte, :username => access_token.info.name, :nickname => access_token.extra.raw_info.domain, :email => access_token.extra.raw_info.domain+'@vk.com', :password => Devise.friendly_token[0,20]) 
  #   end
  # end

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          reffered_by: 0,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  

  has_many :transfers, dependent: :destroy
  has_many :payeers, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :avatars, dependent: :destroy
  #======================================================================
  belongs_to :reffered, :class_name => 'User', foreign_key: 'reffered_by'
  has_many :refferences, :class_name => 'User', foreign_key: 'reffered_by'
  #======================================================================
  belongs_to :invited, :class_name => 'User', foreign_key: 'invited_by'
  has_many :inviteds, :class_name => 'User', foreign_key: 'invited_by'
  #======================================================================
  has_many :identities, dependent: :destroy

  has_many :messages
  has_many :unread_messages
  has_many :subscriptions
  has_many :chat_rooms, through: :subscriptions
  has_many :messages_to_read, class_name: 'Message', through: :unread_messages, source: 'message'

  scope :all_except, ->(user) { where.not(id: user) }

  protected
  def confirmation_required?
    false
  end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :service, :contact]

  def index
  end

  def show
  end

  def service

  end

  def contact

  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homepages/contact.html.erb
<link rel="stylesheet" href="/fonts/gothamPro/stylesheet.css">
<div class="header">
      <div class="container" style="padding-right: 0px;">
         <div class="logo">
            <a href="<%= root_path %>"><img src="<%= image_url('logoen.png')%>" height="47" width="213" alt="Царь горы"></a>
         </div>
         <div class="header_menu_wrap">
         <nav class="header_menu">
            <ul>
               <li><%= link_to '', devnews_index_url, class: 'glyphicon glyphicon-bell' %></li>
               <li><a href="<%= root_path %>"><%= t 'navbar.h' %></a></li>
               <li><a href="<%= service_path %>"><%= t 'navbar.s' %></a></li>
               <li><a href="<%= contact_path %>"><%= t 'navbar.c' %></a></li>
               <% if user_signed_in? && current_user.admin? %>
                <li><a href="<%= admin_root_path %>"><%= t 'navbar.admin' %></a></li>
               <% end %>
               <% if user_signed_in? %>
                <li><a href="<%= profiles_path %>"><%= t 'navbar.profile' %></a></li>
                <li><%= link_to I18n.t('profile.sign_out'), destroy_user_session_path, method: :delete %></li>
                <li><button style="background-color: rgba(255, 255, 255, 0); border-radius: 20px; border-color: #fff;"><a href="<%= new_order_path %>" class="sign_in"><%= t 'navbar.money' %></a></button></li>
                <!-- <li><a data-toggle="modal" data-target=".bs-example-modal-sm">Вывести</a></li> -->
              <% end %>
                <li style='margin-left: 10px;'>
                  <%= link_to_unless_current image_tag("engl.png"), locale: "en" %>
                  <%= link_to_unless_current image_tag("russia.png"), locale: "ru" %> 
                </li>
            </ul>
         </nav>
         <% unless user_signed_in? %>
           <div class="header_sign">
              <a href="<%= new_user_registration_path %>" class="sign_up" style="margin-top: 0;"><%= t 'navbar.register' %></a>
              <a href="<%= new_user_session_path %>" class="sign_in"><%= t 'navbar.sign' %></a>
           </div>
         <% end %>
         <div>
         </div>
         </div>
         <div class="mobile_btn">
            <span></span>
            <span></span>
            <span></span>
         </div>
         <div style="clear: both;"></div>
      </div>
   </div>
<div class="mail_skype_block">
      <h2>Наши контакты</h2>
      <div class="mail_skype">
         <div class="mail_block">
            <div style="background-color: #e4f9f0; top: -50px"><img src="/images/mail.png" alt=""></div>
            <h2 class="support"><a href="#">emailkingofmountain@gmail.com</a></h2>
         </div>
         <div class="skype_block">
            <div style="background-color: #e4f9f0; top: -60px;"><img src="/images/skype.png" alt=""></div>
            <h2 class="support">tarasskypeukr</h2>
         </div>
      </div>
   </div>
   <div class="we_in_soc_network">
      <div class="soc-btn">
         <h2 class="soc-h">Мы в социальной сети:</h2>
         <a href="https://ok.ru/kingofmountain" target="_blank"><img src="/images/odnk.png" alt="OK"></a>
         <a href="https://www.facebook.com/KingofMontain" target="_blank"><img src="/images/fb.png" alt="Facebook"></a>
         <a href="https://vk.com/kingmountain" target="_blank"><img src="/images/vk0.png" alt="VK"></a>
         <a href="https://twitter.com/share?url=https://king-mountain.pro/&text=Царь Горы" target="_blank"><img src="/images/tw.png" alt="Twitter"></a>
      </div>
   </div>
   <%= render '/feedbacks/form' %>
   <div class="footer">
      <div class="container">
        <span class="arrow_up">⌃</span>
         <div class="footer_title">Нравится наш сервис? Поделитесь в социальных сетях:</div>
         <div class="footer_social">
            <a href="http://www.odnoklassniki.ru/dk?st.cmd=addShare&st.s=1&st._surl=https://king-mountain.pro/&st.comments=ЦарьГоры" target="_blank" class="footer_social_item"><img src="/images/ic-ok.png" height="39" width="39" alt="OK"></a>
            <a href="https://www.facebook.com/sharer.php?u=https://king-mountain.pro/" target="_blank" class="footer_social_item"><img src="/images/ic-fb.png" height="26" width="12" alt="Facebook"></a>
            <a href="https://vk.com/share.php?url=https://king-mountain.pro/" target="_blank" class="footer_social_item"><img src="/images/ic-vk.png" height="18" width="30" alt="VK"></a>
            <a href="https://twitter.com/share?url=https://king-mountain.pro/&text=Царь Горы" target="_blank" class="footer_social_item"><img src="/images/ic-tw.png" height="20" width="24" alt="Twitter"></a>
         </div>
         <div class="footer_logo">
            <img src="/images/footer_logo.png" height="45" width="109" alt="Царь горы">
         </div>
         <div class="footer_copyright">
            ООО Игра - “Царь горы” 2017 Все права защищены.
         </div>
      </div>
   </div>

app/views/homepages/service.html.erb
<link rel="stylesheet" href="/fonts/gothamPro/stylesheet.css">
   <div class="header">
      <div class="container" style="padding-right: 0px;">
         <div class="logo">
            <a href="<%= root_path %>"><img src="<%= image_url('logoen.png')%>" height="47" width="213" alt="Царь горы"></a>
         </div>
         <div class="header_menu_wrap">
         <nav class="header_menu">
            <ul>
               <li><%= link_to '', devnews_index_url, class: 'glyphicon glyphicon-bell' %></li>
               <li><a href="<%= root_path %>"><%= t 'navbar.h' %></a></li>
               <li><a href="<%= service_path %>"><%= t 'navbar.s' %></a></li>
               <li><a href="<%= contact_path %>"><%= t 'navbar.c' %></a></li>
               <% if user_signed_in? && current_user.admin? %>
                <li><a href="<%= admin_root_path %>"><%= t 'navbar.admin' %></a></li>
               <% end %>
               <% if user_signed_in? %>
                <li><a href="<%= profiles_path %>"><%= t 'navbar.profile' %></a></li>
                <li><%= link_to I18n.t('profile.sign_out'), destroy_user_session_path, method: :delete %></li>
                <li><button style="background-color: rgba(255, 255, 255, 0); border-radius: 20px; border-color: #fff;"><a href="<%= new_order_path %>" class="sign_in"><%= t 'navbar.money' %></a></button></li>
                <!-- <li><a data-toggle="modal" data-target=".bs-example-modal-sm">Вывести</a></li> -->
              <% end %>
                <li style='margin-left: 10px;'>
                  <%= link_to_unless_current image_tag("engl.png"), locale: "en" %>
                  <%= link_to_unless_current image_tag("russia.png"), locale: "ru" %> 
                </li>
            </ul>
         </nav>
         <% unless user_signed_in? %>
           <div class="header_sign">
              <a href="<%= new_user_registration_path %>" class="sign_up" style="margin-top: 0;"><%= t 'navbar.register' %></a>
              <a href="<%= new_user_session_path %>" class="sign_in"><%= t 'navbar.sign' %></a>
           </div>
         <% end %>
         <div>
         </div>
         </div>
         <div class="mobile_btn">
            <span></span>
            <span></span>
            <span></span>
         </div>
         <div style="clear: both;"></div>
      </div>
   </div>
   <div class="about_project">
      <h3 class="abs-about">О сервисе</h3>
      <p></p>
      <p></p>
      <p>Царь горы – это игровой проект нового формата, которого еще не было на просторах интернета. Разработчики поставили перед собой цель создать честную игру, в которой может заработать каждый. При этом, чтобы шанс выигрыша зависел не от системы, а непосредственно от действий игрока. Так, чтобы честность и прозрачность были ключевыми особенностями проекта. В итоге, поставленная цель была достигнута.</p>

      <p>Суть новой онлайн-игры – добраться до вершины горы, которая состоит из 7 уровней. Чтобы перейти уровень выше ему достаточно заполнить уровень 10/10. Это возможно с помощью реферальной системы или же игра сама добавит людей в уровень. Участнику ничего делать не нужно!</p>

      <p>Аналогичная процедура на всех уровнях.</p>

      <p>Система игры построена на честности и прозрачности всех выполняемых действий. Шанс выигрыша у каждого игрока одинаковый, а риск вылететь из игры сводится к нулю, так как это решение участник принимает самостоятельно, продолжать играть или же вывести свои заработанные деньги! Несмотря на новизну проекта, в дальнейшем он будет только развиваться и становиться более удобным для игроков.</p>

      <p>В отличие от других развлекательных проектов с возможностью заработка, King of mountain – не азартная игра, главная цель которой – оставить вас ни с чем. Напротив, проект заинтересован в том, чтобы вы играли и выигрывали, т. к. его основатели зарабатывают исключительно на комиссиях.</p>

      <p>Чем больше вы выигрываете – тем больше выигрывает King of mountain!</p>

   </div>
   <div class="compare_block about_compare">
      <div class="container">
         <h3>Перспективная игра</h3>
         <p>Cравним с другими</p>
         <div class="col compare_block_no">
            <div class="compare_block_col_title">Рулетка</div>
            <ul>
               <li>Выигрыш зависит только от случая</li>
               <li>Вы можете опираться только на удачу и интуицию</li>
               <li>Азартная игра</li>
               <li>Высокая вероятность остаться ни с чем</li>
               <li>Казино всегда "в плюсе" и заинтересовано в том, чтобы вы проигрывали<li>
            </ul>
            <a href="#">Упустить возможность</a>
         </div>
         <div class="col compare_block_yes">
            <div class="compare_block_col_title">Царь горы</div>
            <ul>
               <li>Вы сами контролируете игру</li>
               <li>Вы можете пользоваться провиантом, дополнениями и реферальной системой, увеличивая свой шанс на выигрыш</li>
               <li>Игра, заработок в которой зависит только от вас</li>
               <li>Максимум, что вы можете потерять - 50 рублей, но и это в случае, если покинете игру</li>
               <li>Сайт зарабатывает исключительно на комиссиях при оплате при оплате вступления и покупки дополнений, по этому мы заинтересованы, чтобы вы играли и выигрывали</li>
            </ul>
            <a href="#">Сделать правильный выбор</a>
         </div>
      </div>
   </div>
   <div class="footer">
      <div class="container">
         <div class="footer_title">Нравится наш сервис? Поделитесь в социальных сетях:</div>
         <div class="footer_social">
            <a href="http://www.odnoklassniki.ru/dk?st.cmd=addShare&st.s=1&st._surl=https://king-mountain.pro/&st.comments=ЦарьГоры" target="_blank" class="footer_social_item"><img src="/images/ic-ok.png" height="39" width="39" alt="OK"></a>
            <a href="https://www.facebook.com/sharer.php?u=https://king-mountain.pro/" target="_blank" class="footer_social_item"><img src="/images/ic-fb.png" height="26" width="12" alt="Facebook"></a>
            <a href="https://vk.com/share.php?url=https://king-mountain.pro/" target="_blank" class="footer_social_item"><img src="/images/ic-vk.png" height="18" width="30" alt="VK"></a>
            <a href="https://twitter.com/share?url=https://king-mountain.pro/&text=Царь Горы" target="_blank" class="footer_social_item"><img src="/images/ic-tw.png" height="20" width="24" alt="Twitter"></a>
         </div>
         <div class="footer_logo">
            <img src="/images/footer_logo.png" height="45" width="109" alt="Царь горы">
         </div>
         <div class="footer_copyright">
            ООО Игра - “Царь горы” 2017 Все права защищены.
         </div>
      </div>
   </div>