config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'

  devise_for :users, controllers: { confirmations: 'users/confirmations',
                                    omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  resources :chats
  resources :common_chat_messages, only: [:create]
  get 'freekassa/new' => 'freekassa#new', as: :freekassa_new
  post 'freekassa/create' => 'freekassa#create', as: :freekassa_create
  get 'freekassa/confirm/:id' => 'freekassa#confirm', as: :freekassa_confirm
  post 'freekassa/result' => 'freekassa#result', as: :freekassa_result
  get 'freekassa/fail' => 'freekassa#fail', as: :freekassa_fail
  get 'freekassa/index' => 'freekassa#index', as: :freekassa_index

  resources :messages
  resources :chat_rooms
  get 'prepend_personal_message' => 'chat_rooms#prepend_personal_message', as: :prepend_personal_message
  ActiveAdmin.routes(self)
  resources :devnews, :homepages, :profiles, :avatars, :improves, :orders, :getmoneys, :getbalances, :feedbacks, :payeers

  #scope ":locale", locale: /en|ru/ do
    post 'buyall/:id' => 'improves#buyall', as: 'buyall'

    put 'buyallproviant/:id' => 'profiles#buyallproviant', as: 'buyallproviant'

    post 'buynumb/:id' => 'profiles#buynumb', as: 'buynumb'
    post 'imroveses/:id' => 'improves#imroveses', as: 'imroveses'


    put 'buyaerodrome/:id' => 'improves#buyaerodrome', as: 'buyaerodrome'
    put 'buyradist/:id' => 'improves#buyradist', as: 'buyradist'
    put 'getbonus/:id' => 'profiles#getbonus', as: 'getbonus'

    get 'service' => 'homepages#service', as: 'service'
    get 'contact' => 'homepages#contact', as: 'contact'
    get 'faq' => 'profiles#faq', as: 'faq'


    get 'mobline' => 'profiles#mobline', as: 'mobline'
    get 'partner' => 'profiles#partner', as: 'partner'

    root 'homepages#index'
  #end

    match '/success' => 'orders#success', via: :get
    match '/fail' => 'orders#fail', via: :get
    match 'payeer/success' => 'payeers#success', via: :get
    match 'payeer/fail' => 'payeers#fail', via: :get

  get '*path', to: redirect("/#{I18n.default_locale}")

  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")
  
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  belongs_to :user

   has_attached_file :image,
                    styles: { medium: '100x100>', thumb: '200x200>'},
                    default_url: '/images/:style/missing.png'
   validates_attachment_content_type :image, 
                    content_type: ['image/jpeg', 'image/gif', 'image/png']

end

app/models/bank.rb
class Bank < ApplicationRecord
 has_many :transfers
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
	has_many :messages, dependent: :destroy
	has_many :subscriptions, dependent: :destroy
	has_many :users, through: :subscriptions

end

app/models/devnew.rb
class Devnew < ApplicationRecord
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/models/getbalance.rb
class Getbalance < ApplicationRecord
end

app/models/getmoney.rb
class Getmoney < ApplicationRecord
  belongs_to :user
end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
  has_many :unread_messages, dependent: :destroy
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
	def is_ik_payment_valid?(ik_cur, ik_am)
	 ( self.currency == ik_cur and self.total == ik_am )
	end
  	belongs_to :user
end

app/models/payeer.rb
class Payeer < ApplicationRecord
  belongs_to :user
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/systemfinance.rb
class Systemfinance < ApplicationRecord
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user
  belongs_to :bank
end

app/models/user.rb
class User < ApplicationRecord
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
    omniauth_providers: [:facebook, :twitter, :vkontakte]

  validates :name, presence: true, length: {maximum: 50}
  # validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  after_create :send_admin_mail

  # онлайн пользователи - User.online.count
  scope :online, lambda{ where("last_seen >= ?", 10.minutes.ago) }

  # def online?
  #   $redis_onlines.exists( self.id )
  # end

  def send_admin_mail

    self.send_confirmation_instructions
  end
  # after_create :send_admin_mail  

  # def send_admin_mail    
  #   Devise::Mailer.send_new_user_message(self).deliver  
  # end

  # def self.find_for_vkontakte_oauth(access_token)
  #   if user = User.where(:url => access_token.info.urls.Vkontakte).first
  #     user
  #   else 
  #     User.create!(:provider => access_token.provider, :url => access_token.info.urls.Vkontakte, :username => access_token.info.name, :nickname => access_token.extra.raw_info.domain, :email => access_token.extra.raw_info.domain+'@vk.com', :password => Devise.friendly_token[0,20]) 
  #   end
  # end

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          reffered_by: 0,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  

  has_many :transfers, dependent: :destroy
  has_many :payeers, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :avatars, dependent: :destroy
  #======================================================================
  belongs_to :reffered, :class_name => 'User', foreign_key: 'reffered_by'
  has_many :refferences, :class_name => 'User', foreign_key: 'reffered_by'
  #======================================================================
  belongs_to :invited, :class_name => 'User', foreign_key: 'invited_by'
  has_many :inviteds, :class_name => 'User', foreign_key: 'invited_by'
  #======================================================================
  has_many :identities, dependent: :destroy

  has_many :messages
  has_many :unread_messages
  has_many :subscriptions
  has_many :chat_rooms, through: :subscriptions
  has_many :messages_to_read, class_name: 'Message', through: :unread_messages, source: 'message'

  scope :all_except, ->(user) { where.not(id: user) }

  protected
  def confirmation_required?
    false
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_left_bar.html.erb
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">
    <div class="profile_pic">

      <% ava = current_user.avatars.last %>
      <% if ava.nil? %>
          <%= image_tag('img.jpg', class: 'img-circle profile_img') %>
      <% else %>
          <img src="<%= image_path ava.image.url() %>" alt="Profile Image" class="img-circle profile_img">
      <% end %>


    </div>
    <div class="profile_info">
      <span>Welcome,</span>
      <h2> <%= current_user.name %></h2>
    </div>
  </div>
  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <h3>Панель управления</h3>
        <ul class="nav side-menu">
          <li><a><i class="fa fa-home"></i> Главная <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="<%= root_path %>">Главная</a></li>
              <li><a href="<%= new_order_path %>">Пополнить</a></li>
              <li><a href="<%= mobline_path %>">Профиль</a></li>
              <li><a href="<%= chats_path %>">Общий чат</a></li>
            </ul>
          </li>
          <li><a><i class="fa fa-edit"></i> Тарифные планы <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="<%= partner_path %>">Моблан 50</a></li>
              <li><a href="<%= partner_path %>">Элбрус 500</a></li>
              <li><a href="<%= partner_path %>">Килиманджаро 2500</a></li>
              <li><a href="<%= partner_path %>">Эверест 5000</a></li>
            </ul>
          </li>
          <li><a><i class="fa fa-desktop"></i> Рефералы <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="<%= faq_path %>">Друзья</a></li>
              <li><a href="<%= faq_path %>">Частые вопросы</a></li>
              <li><a href="<%= contact_path %>">Поддержка</a></li>
              <li><a href="<%= partner_path %>">Контакты</a></li>
            </ul>
        </ul>
      </div>
    </div>
    <!-- <div class="menu_section">
      <h3>Live On</h3>
      <ul class="nav side-menu">
        <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="e_commerce.html">E-commerce</a></li>
            <li><a href="projects.html">Projects</a></li>
            <li><a href="project_detail.html">Project Detail</a></li>
            <li><a href="contacts.html">Contacts</a></li>
            <li><a href="profile.html">Profile</a></li>
          </ul>
        </li>
      </ul>
    </div> -->

  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->
  <div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
      <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
      <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
      <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
  </div>
  <!-- /menu footer buttons -->
</div>

app/views/shared/_top_nav.html.erb
<!-- top navigation -->
<!-- top navigation -->
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">


            <% ava = current_user.avatars.last %>
            <% if ava.nil? %>
                <%= image_tag('img.jpg') %>
            <% else %>
                <img src="<%= image_path ava.image.url(:thumb) %>" alt="Profile Image">
            <% end %>
            <%= current_user.name %>

            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;"> Profile</a></li>
            <li>
              <a href="<%= edit_user_registration_path %>">
                <span class="badge bg-red pull-right">50%</span>
                <span>Settings</span>
              </a>
            </li>
            <li><a href="javascript:;">Help</a></li>
            <li><i class="fa fa-sign-out pull-right"></i> <%= link_to 'Выйти', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>

        <li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green" id="unread_messages_count">
                    <%= current_user.unread_messages.count %>
                  </span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">

            <% current_user.unread_messages.last(5).reverse.each do |unread| %>
                <%= render 'messages/message_notify', message: unread.message %>
            <% end %>

            <li>
              <div class="text-center">
                <a href="<%= chat_rooms_path %>">
                  <strong>See All Alerts</strong>
                  <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</div>
<!-- /top navigation -->